services:

  mssqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Server2008!"
      ACCEPT_EULA: "Y"
    
  openid.authority:
    image: authority-image
    build:
      context: .
      dockerfile: DockerOpenIdAuthority/Dockerfile
    ports:
      - "7000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - mssqlserver
    container_name: openid-authority

