services:

#  mssqlserver:
#    image: mcr.microsoft.com/mssql/server:2019-latest
#    container_name: ctr-mssqlserver
#    ports:
#      - "1433:1433"
#    environment:
#      SA_PASSWORD: "Server2008!"
#      ACCEPT_EULA: "Y"
#
#  openid.authority:
#    image: img-authority
#    build:
#      context: .
#      dockerfile: DockerOpenIdAuthority/Dockerfile
#    ports:
#      - "7000:8080"
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Production
#    depends_on:
#      - mssqlserver
#    container_name: ctr-openid-authority

  openid.blazorwasm:
    image: img-blazorwasm
    build:
      context: .
      args:
        BLAZOR_ENVIRONMENT: Production
      dockerfile: DockerOpenIdBlazorWasm/Dockerfile
    ports:
      - "7002:80"
    container_name: ctr-openid-blazorwasm
